export const LOGIN = "LOGIN";
export const LOGIN_SECCESS = "LOGIN_SECCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";


export const REGISTER = "REGISTER";
export const REGISTER_SECCESS = "REGISTER_SECCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGOUT = 'LOGOUT'


export const GET_CLIENT = "GET_CLIENT";
export const GET_CLIENT_SECCESS = "GET_CLIENT_SECCESS";
export const GET_CLIENT_FAIL = "GET_CLIENT_FAIL";


export const GET_ORGANISATEUR = "GET_ORGANISATEUR";
export const GET_ORGANISATEUR_SECCESS = "GET_CORGANISATEUR_SECCESS";
export const GET_ORGANISATEUR_FAIL = "GET_ORGANISATEUR_FAIL";

export const GET_ADMIN = "GET_ADMIN";
export const GET_ADMIN_SECCESS = "GET_ADMIN_SECCESS";
export const GET_ADMIN_FAIL = "GET_ADMIN_FAIL";


export const REGISTER_ORGANISATEUR = "REGISTER_ORGANISATEUR";
export const REGISTER_ORGANISATEUR_SECCESS = "REGISTER_ORGANISATEUR_SECCESS";
export const REGISTER_ORGANISATEUR_FAIL = "REGISTER_ORGANISATEUR_FAIL";


export const REGISTER_ADMIN = "REGISTER_ADMIN";
export const REGISTER_ADMIN_SECCESS = "REGISTER_ADMIN_SECCESS";
export const REGISTER_ADMIN_FAIL = "REGISTER_ADMIN_FAIL";


export const CREATE_EVENT = "CREATE_EVENT";
export const CREATE_EVENT_SECCESS = "CREATE_EVENT_SECCESS";
export const CREATE_EVENT_FAIL = "CREATE_EVENT_FAIL";


export const GET_EVENT = "GET_EVENT";
export const GET_EVENT_SECCESS = "GET_EVENT_SECCESS";
export const GET_EVENT_FAIL = "GET_EVENT_FAIL";


export const GET_ONE_EVENT = "GET_ONE_EVENT";
export const GET_ONE_EVENT_SECCESS = "GET_ONE_EVENT_SECCESS";
export const GET_ONE_EVENT_FAIL = "GET_ONE_EVENT_FAIL";

export const CREATE_TICKET = 'CREATE_TICKET';
export const CREATE_TICKET_FAIL = 'CREATE_TICKET_FAIL';
export const CREATE_TICKET_SECCESS = 'CREATE_TICKET_SECCESS';



export const GET_MY_EVENTS = 'GET_MY_EVENTS'
export const GET_MY_EVENTS_FAIL = 'GET_MY_EVENTS_FAIL'
export const GET_MY_EVENTS_SECCESS = 'GET_MY_EVENTS_SECCESS'


export const GET_USER_INFO = "GET_USER_INFO";
export const GET_USER_INFO_SECCESS = "GET_USER_INFO_SECCESS";
export const GET_USER_INFO_FAIL = "GET_USER_INFO_FAIL";